### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by Sayan-dev** [technojam/portfolio_generator#14]
Error
![image](https://user-images.githubusercontent.com/42710260/94923729-f3d26b80-04d9-11eb-99ac-31bdff88db14.png)

and this too
![image](https://user-images.githubusercontent.com/42710260/94923942-4c096d80-04da-11eb-90f1-298a96f3903f.png)

**Comment by Sayan-dev** [comment]
Working on it

**Comment by Ritwik880** [comment]
Hii @Sayan-dev, change your directory  to client for frontend and run npm i or npm install and then run npm start

**Comment by Sayan-dev** [comment]
![image](https://user-images.githubusercontent.com/42710260/94924715-afe06600-04db-11eb-816a-184efe6d08d8.png)
Now we have this error.....the folder is missing

**Comment by Ritwik880** [comment]
You are getting this error because currently the other folders are empty. Go to Main.js file in container section and comment out div section.
